# Service account used by the pods to obtain pod metadata.
apiVersion: v1
kind: ServiceAccount
metadata:
  # Do not change name, its hard-coded in operator
  name: aerospike-cluster
  namespace: aerospike

---
# Service account used by the pods to obtain pod metadata.
apiVersion: v1
kind: ServiceAccount
metadata:
  # Do not change name, its hard-coded in operator
  name: aerospike-cluster
  namespace: aerospike1

---
# Service account used by the pods to obtain pod metadata.
apiVersion: v1
kind: ServiceAccount
metadata:
  # Do not change name, its hard-coded in operator
  name: aerospike-cluster
  namespace: aerospike2

---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-cluster
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  verbs:
  - get
  - list
- apiGroups:
  - aerospike.com
  resources:
  - '*'
  verbs:
  - '*'

---

# RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aerospike-cluster
subjects:
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike1
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike2
roleRef:
  kind: ClusterRole
  name: aerospike-cluster
  apiGroup: rbac.authorization.k8s.io

# # More restrictive binding
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: aerospike-cluster
#   namespace: aerospike
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: aerospike-cluster
# subjects:
# - kind: ServiceAccount
#   name: aerospike-cluster
#   namespace: aerospike
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: aerospike-cluster
#   namespace: aerospike1
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: aerospike-cluster
# subjects:
# - kind: ServiceAccount
#   name: cass-operator
#   namespace: aerospike1
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: aerospike-cluster
#   namespace: aerospike2
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: aerospike-cluster
# subjects:
# - kind: ServiceAccount
#   name: cass-operator
#   namespace: aerospike2